import { Express } from "express";
import { User } from "./user.type";
import { registerUser } from "./controller";
import { status } from "../../../core/request-error";
import { UserModel } from "./model";
import { decodeToken } from "../../../lib/decode-token";

export const UserEndpoint = (app: Express) => {
  const apiGroup = "/user/";
  const endpoint = (e: string) => apiGroup + e;

  /**
   * Responsible for validating user against DB,
   * using user id, generated by auth0
   *
   * @api {get} /users/validate
   * @apiName ValidateUser
   * @apiGroup user
   */
  app.post(endpoint("validate/"), async (req, res) => {
    try {
      const user = req.body as User;
      const userId = decodeToken(req.headers)?.iss as string;

      await UserModel.validate({ ...user, packages: [] });
      await registerUser(user, userId);

      res.status(200).send();
    } catch (err) {
      res.status(status.error.badReq).send(err);
    }
  });
};
